### ISSUE TITLE
Curse Download has wrong version number

### ISSUE THREAD

**Issue by ttek** [Phanx/oUF_Phanx#15]
the toc file needs to be updated for the curse download

**Comment by Phanx** [comment]
https://github.com/Phanx/oUF_Phanx/blob/master/oUF_Phanx.toc#L1
https://github.com/Phanx/oUF_Phanx/blob/master/Config/oUF_Phanx_Config.toc#L1

Looks fine to me. If the Curse Client gave you an old version, there's nothing I can do about that.
