### ISSUE TITLE
Auras.lua:925: bad argument #1 to 'bit_band'

### ISSUE THREAD

**Issue by Dragonfail** [Phanx/oUF_Phanx#6]
So updated through curse client tonight and though it shows I have it installed it's not there no bars everything is back to ucky blizz bars. I go to options and it's a blank box. I type /pouf and i get the yellow message about typing for help commands or whatever it says. I went to the trouble shoot link and followed all the advice there and it didn't work. Bug Sack did have this logged though. this is completely Greek to me but as it has the oUF_Phanx at the start I'm taking a guess it has to do with my issue?  Thanx for your time.

````
3x oUF_Phanx\Auras-Auras.lua:925: bad argument #1 to 'bit_band' (number expected, got table)
[C]: ?
oUF_Phanx\Auras-Auras.lua:925: in function `UpdateAuraList'
oUF_Phanx\Core.lua:289: in function `?'
oUF_Phanx\Core.lua:241: in function <oUF_Phanx\Core.lua:240>
````

**Comment by Phanx** [comment]
Going to assume this is fixed since nobody has said anything about it since the update.
