### ISSUE TITLE
Can I see the target buff?

### ISSUE THREAD

**Issue by hkongm** [Phanx/oUF_Phanx#8]
I cannot see the target's buff icon.
And I don't find out where to turn on this option in config.
Can u add this option switch in next version?
Thx.

**Comment by Phanx** [comment]
Buffs are automatically shown on the target. There is no option to turn them off. Is there a specific buff you were expecting to see? Or are you not seeing ANY buffs, ever?

**Comment by hkongm** [comment]
I can see nothing.
I want dispel enemy's buff, and I'm a priest.

**Comment by Phanx** [comment]
1. What version of the addon are you using? (Interface Options > oUF Phanx > About)

2. Do you have an error addon like [http://www.curse.com/addons/wow/bugger]Bugger[/URL], BugSack, or Swatter running? If not, please install one to check for errors. (The "Display Lua Errors" option in the default Interface Options unfortunately can't detect errors that happen during login.)

3. Are there any errors when you log in or select a target? If so, what are the errors?

**Comment by Phanx** [comment]
Also, it just occurred to me -- enemy buffs you can dispel (or debuffs on friendly players you can dispel) are not shown as icons above the frame. They just make the border of the frame change color. If the target has a Magic buff or debuff you can dispel, the frame border turns blue.

**Comment by Phanx** [comment]
Issue closed due to lack of response. If you are still having a problem, please reply with the information requested in my previous posts.
